# Generated by Django 5.1.3 on 2024-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
