# Generated by Django 5.1.3 on 2024-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='shared_link',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
