# Generated by Django 5.1.3 on 2024-12-08 12:32

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='auto_deleted_at',
            field=models.DateTimeField(default=files.models.default_auto_deleted_at),
        ),
    ]
