# Generated by Django 5.1.3 on 2025-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_auto_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
