# Generated by Django 5.1.3 on 2025-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, help_text='Date and time when the file was last downloaded', null=True, verbose_name='Last Downloaded'),
        ),
    ]
